### ISSUE TITLE
请问可以分享一下weights_19.pth吗？

### ISSUE THREAD

**Issue by LuckYX07** [Kaeless/U-Net-liver#2]
请问可以分享一下weights_19.pth吗？万分感谢

**Comment by MaoFuyou** [comment]
> 请问可以分享一下weights_19.pth吗？万分感谢

我的邮箱是mfy15541207057@gmail.com 我有weights_19.pth我给你发！

**Comment by LuckYX07** [comment]
> > 请问可以分享一下weights_19.pth吗？万分感谢
> 
> 我的邮箱是[mfy15541207057@gmail.com](mailto:mfy15541207057@gmail.com) 我有weights_19.pth我给你发！

已经发邮件至您邮箱了！非常感谢！

**Comment by MaoFuyou** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kaeless/U-Net-liver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kaeless/U-Net-liver] 请问可以分享一下weights_19.pth吗？ (Issue #2)





   
请问可以分享一下weights_19.pth吗？万分感谢
  
***@***.*** 我有weights_19.pth我给你发！
  
已经发邮件至您邮箱了！非常感谢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

weights_49.pth (118.51M, 2023年12月24日 10:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7339333108eea599441477bb1436004e484d5702565254041d5c0000021b0b00525b1e010303034c0301555207545451020d0508323832165550545946456d55091743455a360f&code=0931262a
